# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_show_pdf',
            field=models.BooleanField(default=False, verbose_name='Can show PDF'),
        ),
    ]
