# Generated by Django 5.2.14 on 2026-05-08 08:06

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_pg_trgm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="can_show_pdf",
        ),
        migrations.RemoveField(
            model_name="item",
            name="private_pdf",
        ),
        migrations.AlterField(
            model_name="item",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=items.models.Item.upload_dest,
                verbose_name="PDF file (admin-only; not exposed for download)",
            ),
        ),
    ]
