# Generated by Django 5.2.14 on 2026-06-02 04:42

import django.core.validators
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_remove_item_show_abstract"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="pdf_is_public",
            field=models.BooleanField(
                default=False,
                help_text="Tick to show this item's PDF to visitors. Off by default — leave off for copyright-restricted PDFs.",
                verbose_name="PDF is public",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=items.models.Item.upload_dest,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])],
                verbose_name="PDF file (admin-only unless 'PDF is public' is ticked)",
            ),
        ),
    ]
