# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_string', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=50)),
                ('item_pk', models.IntegerField()),
                ('extra_info', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
