# Generated by Django 5.2.14 on 2026-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagehit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagehit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
